# Travis configuration

language: python

dist: trusty
sudo: false


before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

install:
  - pip2 install .
  - pip2 install flake8
  - pip2 install -r requirements-optional.txt

script:
  - python setup.py test

before_deploy:
  # Build a source and wheel artifact
  - python setup.py sdist
  - python setup.py bdist_wheel
